AC_PROPERTIES = {
    "SpeedMS": {"id": 0, "optional": False, "result": 1},
    "SpeedMPH": {"id": 1, "optional": False, "result": 1},
    "SpeedKMH": {"id": 2, "optional": False, "result": 1},
    "Gas": {"id": 3, "optional": False, "result": 1},
    "Brake": {"id": 4, "optional": False, "result": 1},
    "Clutch": {"id": 5, "optional": False, "result": 1},
    "Gear": {"id": 6, "optional": False, "result": 1},
    "Aero": {"id": 7, "optional": False, "result": 1},
    "BestLap": {"id": 8, "optional": False, "result": 1},
    "CamberRad": {"id": 9, "optional": False, "result": 4},
    "AccG": {"id": 10, "optional": False, "result": 3},
    "CGHeight": {"id": 11, "optional": False, "result": 1},
    "DriftBestLap": {"id": 12, "optional": False, "result": 1},
    "DriftLastLap": {"id": 13, "optional": False, "result": 1},
    "DriftPoints": {"id": 14, "optional": False, "result": 1},
    "DriveTrainSpeed": {"id": 15, "optional": False, "result": 1},
    "DY": {"id": 16, "optional": False, "result": 4},
    "RPM": {"id": 17, "optional": False, "result": 1},
    "Load": {"id": 18, "optional": False, "result": 4},
    "InstantDrift": {"id": 19, "optional": False, "result": 1},
    "IsDriftInvalid": {"id": 20, "optional": False, "result": 1},
    "IsEngineLimiterOn": {"id": 21, "optional": False, "result": 1},
    "LapCount": {"id": 22, "optional": False, "result": 1},
    "LapInvalidated": {"id": 23, "optional": False, "result": 1},
    "LapTime": {"id": 24, "optional": False, "result": 1},
    "LastFF": {"id": 25, "optional": False, "result": 1},
    "LastLap": {"id": 26, "optional": False, "result": 1},
    "LocalAngularVelocity": {"id": 27, "optional": False, "result": 3},
    "LocalVelocity": {"id": 28, "optional": False, "result": 3},
    "Mz": {"id": 29, "optional": False, "result": 4},
    "NdSlip": {"id": 30, "optional": False, "result": 4},
    "NormalizedSplinePosition": {"id": 31, "optional": False, "result": 1},
    "PerformanceMeter": {"id": 32, "optional": False, "result": 1},
    "SlipAngle": {"id": 33, "optional": False, "result": 4},
    "SlipAngleContactPatch": {"id": 34, "optional": False, "result": 4},
    "SlipRatio": {"id": 35, "optional": False, "result": 4},
    "SpeedTotal": {"id": 36, "optional": False, "result": 3},
    "Steer": {"id": 37, "optional": False, "result": 1},
    "SuspensionTravel": {"id": 38, "optional": False, "result": 4},
    "TurboBoost": {"id": 39, "optional": False, "result": 1},
    "TyreDirtyLevel": {"id": 40, "optional": False, "result": 4},
    "TyreContactNormal": {"id": 41, "optional": False, "result": 3},
    "TyreContactPoint": {"id": 42, "optional": False, "result": 3},
    "TyreHeadingVector": {"id": 43, "optional": False, "result": 1},
    "TyreLoadedRadius": {"id": 44, "optional": False, "result": 4},
    "TyreRadius": {"id": 45, "optional": False, "result": 4},
    "TyreRightVector": {"id": 46, "optional": False, "result": 1},
    "TyreSlip": {"id": 47, "optional": False, "result": 4},
    "TyreSurfaceDef": {"id": 48, "optional": False, "result": 1},
    "TyreVelocity": {"id": 49, "optional": False, "result": 1},
    "Velocity": {"id": 50, "optional": False, "result": 3},
    "WheelAngularSpeed": {"id": 51, "optional": False, "result": 4},
    "WorldPosition": {"id": 52, "optional": False, "result": 3},
    "Caster": {"id": 53, "optional": False, "result": 1},
    "CurrentTyresCoreTemp": {"id": 54, "optional": False, "result": 4},
    "LastTyresTemp": {"id": 55, "optional": False, "result": 3},
    "DynamicPressure": {"id": 56, "optional": False, "result": 4},
    "RideHeight": {"id": 57, "optional": False, "result": 2},
    "ToeInDeg": {"id": 58, "optional": False, "result": 1},
    "CamberDeg": {"id": 59, "optional": False, "result": 4},
    "KersCharge": {"id": 60, "optional": False, "result": 1},
    "KersInput": {"id": 61, "optional": False, "result": 1},
    "DrsAvailable": {"id": 62, "optional": False, "result": 1},
    "DrsEnabled": {"id": 63, "optional": False, "result": 1},
    "EngineBrake": {"id": 64, "optional": False, "result": 1},
    "ERSRecovery": {"id": 65, "optional": False, "result": 1},
    "ERSDelivery": {"id": 66, "optional": False, "result": 1},
    "ERSHeatCharging": {"id": 67, "optional": False, "result": 1},
    "ERSCurrentKJ": {"id": 68, "optional": False, "result": 1},
    "ERSMaxJ": {"id": 69, "optional": False, "result": 1},
    "RaceFinished": {"id": 70, "optional": False, "result": 1},
    "P2PStatus": {"id": 71, "optional": False, "result": 1},
    "P2PActivations": {"id": 72, "optional": False, "result": 1},
}


def AC_Get(car, name, optional):
    entry = AC_PROPERTIES[name]

    if entry["optional"]:
        return ac.getCarState(car, entry["id"], entry["optional"])
    else:
        return ac.getCarState(car, entry["id"])